# -*- coding: utf-8 -*-
"""Diccionario

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iGIXW7mGRQp_VkwZQWnUyswhR7I26Aqp
"""

import random
actividades = ["jugar futbol","jugar video juegos","nadar","salir con mi familia"]
print  (random.choice (actividades))

meme_dict = {
            "CRINGE": "Algo excepcionalmente raro o embarazoso",
            "LOL": "Una respuesta común a algo gracioso",
            "BACANO": "Algo que esta muy chevere",
            }

word = input("Escribe una palabra que no entiendas (¡con mayúsculas!): ")

meme_dict = {
            "CRINGE": "Algo excepcionalmente raro o embarazoso",
            "LOL": "Una respuesta común a algo gracioso",
            "BACANO": "Algo que esta muy chevere",
            }
word = input("Escribe una palabra que no entiendas (¡con mayúsculas!): ")
if word in meme_dict.keys():
   print(meme_dict [word])
else:
     print("Todavia no encontramos tu palabra pero tranqui ya lo resolvemos.")